controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_logout:
    path: /logout
    controller: App\Controller\LogoutController::logout
delete_comment:
    path: '/comment/{id}/delete'
    controller: 'App\Controller\CommentController::deleteComment'